### PR TITLE
Add editor template for collections

### PR DESCRIPTION
**Pull request by hazzik**

### CODE REVIEW

**Comment by danludwig** [comment]
Hi hazzik,

Thanks for the pull request. I have reviewed your contributions, and though I like the idea of using a shared Collection.cshtml editor template for the helper, 4 unit tests fail as of your last commit.

Would you please extend your contribution to remove/create/update unit tests to that your new code is covered?

Thanks,

Dan Ludwig

**Comment by hazzik** [comment]
@danludwig, sure

**Comment by hazzik** [comment]
Unit tests were fixed, thanks for the note!

**Comment by danludwig** [comment]
Thanks, merging in now. Also I will update the nuspec `<authors>` to include you. Would you prefer your real full name or your github username?

**Comment by hazzik** [comment]
@danludwig thanks, write it as "hazzik".

**Comment by danludwig** [comment]
Commits merged. I added some trailing commits for the nuget package, as well as fixing a jquery bug in the demo and upgrading the solution to be openable in VS 2012. If you are maintaining your own fork, you can pull the master to get these commits.

**Pull request merged**
